### ISSUE TITLE
ReferenceError: FormData is not defined (fails Next.js build)

### ISSUE THREAD

**Issue by ibreslauer** [dan-kwiat/openai-edge#10]
Calling `openai.createChatCompletion()` from a Next.js route handler causes the build to break with the following missing dependency:

```
- info Collecting page data ..ReferenceError: FormData is not defined
    at Object.19445 (/home/<username>/repos/<repo>/.next/server/chunks/901.js:2202:30)
    at __webpack_require__ (/home/<username>/repos/<repo>/.next/server/webpack-runtime.js:25:43)
    at Module.91102 (/home/<username>/repos/<repo>/.next/server/app/api/<endpoint>/route.js:76:12)
    at __webpack_require__ (/home/<username>/repos/<repo>/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/home/<username>/repos/<repo>/.next/server/app/api/<endpoint>/route.js:301:39)
    at /home/<username>/repos/<repo>/.next/server/app/api/<endpoint>/route.js:302:78
    at Function.__webpack_require__.X (/home/<username>/repos/<repo>/.next/server/webpack-runtime.js:138:21)
    at /home/<username>/repos/<repo>/.next/server/app/api/<endpoint>/route.js:302:47
    at Object.<anonymous> (/home/<username>/repos/<repo>/.next/server/app/api/<endpoint>/route.js:305:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

> Build error occurred
Error: Failed to collect page data for /api/webhooks
    at /home/<username>/repos/<repo>/node_modules/next/dist/build/utils.js:1161:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
}
```

Here's the code snipped from my function I'm calling from an API route:

```
const response = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: [
      {
        role: "system",
        content:
          "You are a helpful assistant.",
      },
      { role: "user", content: prompt },
    ],
  });
  const completionResponse =
    (await response.json()) as ResponseTypes["createChatCompletion"];
  return completionResponse.choices[0].message?.content || "<fallback message>";
```

I temporarily resolved this by using the [official library](https://www.npmjs.com/package/openai).

Is there something specific I should be doing for this function call to not break the build?

Thanks!

**Comment by dan-kwiat** [comment]
@ibreslauer this library currently works in environments which support `FormData`, so you'll need Node v18. I'll update the docs to mention this, thank you. For reference:
https://developer.mozilla.org/en-US/docs/Web/API/FormData
